apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-db-deployment
  namespace: movie-microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-db
  template:
    metadata:
      labels:
        app: users-db
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: users-db-secret
              key: database
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: users-db-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: users-db-secret
              key: password
        ports:
        - containerPort: 5432
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        volumeMounts:
        - name: users-db-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: users-db-data
        persistentVolumeClaim:
          claimName: users-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: users-db-service
  namespace: movie-microservices
spec:
  selector:
    app: users-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: users-db-pvc
  namespace: movie-microservices
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
