apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
  namespace: movie-microservices
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: REPLACE_WITH_YOUR_REGISTRY/movie-microservices/api-gateway:latest
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: movie-microservices-config
              key: ASPNETCORE_ENVIRONMENT
        - name: Jwt__Key
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: key
        - name: Jwt__Issuer
          valueFrom:
            configMapKeyRef:
              name: movie-microservices-config
              key: JWT_ISSUER
        - name: Jwt__Audience
          valueFrom:
            configMapKeyRef:
              name: movie-microservices-config
              key: JWT_AUDIENCE
        - name: Services__UserService
          valueFrom:
            configMapKeyRef:
              name: movie-microservices-config
              key: USER_SERVICE_URL
        - name: Services__MovieService
          valueFrom:
            configMapKeyRef:
              name: movie-microservices-config
              key: MOVIE_SERVICE_URL
        - name: Services__RecommendationService
          valueFrom:
            configMapKeyRef:
              name: movie-microservices-config
              key: RECOMMENDATION_SERVICE_URL
        - name: Services__RatingService
          valueFrom:
            configMapKeyRef:
              name: movie-microservices-config
              key: RATING_SERVICE_URL
        - name: Services__WatchlistService
          valueFrom:
            configMapKeyRef:
              name: movie-microservices-config
              key: WATCHLIST_SERVICE_URL
        - name: Services__NotificationService
          valueFrom:
            configMapKeyRef:
              name: movie-microservices-config
              key: NOTIFICATION_SERVICE_URL
        - name: Services__CmsService
          valueFrom:
            configMapKeyRef:
              name: movie-microservices-config
              key: CMS_SERVICE_URL
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: movie-microservices
spec:
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-gateway-hpa
  namespace: movie-microservices
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-gateway-deployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
