apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms-service-deployment
  namespace: movie-microservices
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cms-service
  template:
    metadata:
      labels:
        app: cms-service
    spec:
      containers:
      - name: cms-service
        image: REPLACE_WITH_YOUR_REGISTRY/movie-microservices/cms-service:latest
        ports:
        - containerPort: 8081
        env:
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: movie-microservices-config
              key: ASPNETCORE_ENVIRONMENT
        - name: ConnectionStrings__DefaultConnection
          value: "Host=cms-db-service;Port=5432;Database=$(CMS_DB_NAME);Username=$(CMS_DB_USER);Password=$(CMS_DB_PASSWORD)"
        - name: CMS_DB_NAME
          valueFrom:
            secretKeyRef:
              name: cms-db-secret
              key: database
        - name: CMS_DB_USER
          valueFrom:
            secretKeyRef:
              name: cms-db-secret
              key: username
        - name: CMS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cms-db-secret
              key: password
        - name: Jwt__Key
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: key
        - name: Jwt__Issuer
          valueFrom:
            configMapKeyRef:
              name: movie-microservices-config
              key: JWT_ISSUER
        - name: Jwt__Audience
          valueFrom:
            configMapKeyRef:
              name: movie-microservices-config
              key: JWT_AUDIENCE
        - name: FileUpload__MaxFileSize
          value: "5242880"
        - name: FileUpload__AllowedExtensions
          value: ".jpg,.jpeg,.png,.gif"
        - name: FileUpload__UploadPath
          value: "uploads"
        - name: Storage__Provider
          value: "local"
        - name: Storage__LocalPath
          value: "/app/uploads"
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: cms-uploads
          mountPath: /app/uploads
      volumes:
      - name: cms-uploads
        persistentVolumeClaim:
          claimName: cms-uploads-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: cms-service
  namespace: movie-microservices
spec:
  selector:
    app: cms-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cms-uploads-pvc
  namespace: movie-microservices
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cms-service-hpa
  namespace: movie-microservices
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cms-service-deployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
