apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service-deployment
  namespace: movie-microservices
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: REPLACE_WITH_YOUR_REGISTRY/movie-microservices/notification-service:latest
        ports:
        - containerPort: 3004
        env:
        - name: PORT
          value: "3004"
        - name: ENVIRONMENT
          value: "production"
        - name: DATABASE_HOST
          value: "notification-db-service"
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: notification-db-secret
              key: username
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: notification-db-secret
              key: password
        - name: DATABASE_DBNAME
          valueFrom:
            secretKeyRef:
              name: notification-db-secret
              key: database
        - name: DATABASE_SSLMODE
          value: "disable"
        - name: REDIS_HOST
          value: "redis-service"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
          value: ""
        - name: REDIS_DB
          value: "0"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: key
        - name: EMAIL_PROVIDER
          value: "sendgrid"
        - name: EMAIL_API_KEY
          valueFrom:
            secretKeyRef:
              name: email-api-key
              key: key
        - name: EMAIL_FROM_EMAIL
          value: "noreply@movie-microservices.com"
        - name: EMAIL_FROM_NAME
          value: "Movie Microservices"
        - name: PUSH_PROVIDER
          value: "fcm"
        - name: PUSH_API_KEY
          valueFrom:
            secretKeyRef:
              name: fcm-api-key
              key: key
        - name: PUSH_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: fcm-auth-token
              key: token
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3004
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 3004
          initialDelaySeconds: 5
          periodSeconds: 5
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: movie-microservices
spec:
  selector:
    app: notification-service
  ports:
    - protocol: TCP
      port: 3004
      targetPort: 3004
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: notification-service-hpa
  namespace: movie-microservices
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: notification-service-deployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
