apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation-service-deployment
  namespace: movie-microservices
spec:
  replicas: 2
  selector:
    matchLabels:
      app: recommendation-service
  template:
    metadata:
      labels:
        app: recommendation-service
    spec:
      containers:
      - name: recommendation-service
        image: REPLACE_WITH_YOUR_REGISTRY/movie-microservices/recommendation-service:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgresql://$(RECOMMENDATIONS_DB_USER):$(RECOMMENDATIONS_DB_PASSWORD)@recommendations-db-service:5432/$(RECOMMENDATIONS_DB_NAME)"
        - name: RECOMMENDATIONS_DB_NAME
          valueFrom:
            secretKeyRef:
              name: recommendations-db-secret
              key: database
        - name: RECOMMENDATIONS_DB_USER
          valueFrom:
            secretKeyRef:
              name: recommendations-db-secret
              key: username
        - name: RECOMMENDATIONS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: recommendations-db-secret
              key: password
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: movie-microservices-config
              key: REDIS_URL
        - name: USER_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: movie-microservices-config
              key: USER_SERVICE_URL
        - name: MOVIE_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: movie-microservices-config
              key: MOVIE_SERVICE_URL
        - name: RATING_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: movie-microservices-config
              key: RATING_SERVICE_URL
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: key
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: movie-microservices-config
              key: LOG_LEVEL
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: recommendation-service
  namespace: movie-microservices
spec:
  selector:
    app: recommendation-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: recommendation-service-hpa
  namespace: movie-microservices
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: recommendation-service-deployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
