apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
  namespace: movie-microservices
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: REPLACE_WITH_YOUR_REGISTRY/movie-microservices/user-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: movie-microservices-config
              key: ASPNETCORE_ENVIRONMENT
        - name: ConnectionStrings__DefaultConnection
          value: "Host=users-db-service;Port=5432;Database=$(USERS_DB_NAME);Username=$(USERS_DB_USER);Password=$(USERS_DB_PASSWORD)"
        - name: USERS_DB_NAME
          valueFrom:
            secretKeyRef:
              name: users-db-secret
              key: database
        - name: USERS_DB_USER
          valueFrom:
            secretKeyRef:
              name: users-db-secret
              key: username
        - name: USERS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: users-db-secret
              key: password
        - name: Jwt__Key
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: key
        - name: Jwt__Issuer
          valueFrom:
            configMapKeyRef:
              name: movie-microservices-config
              key: JWT_ISSUER
        - name: Jwt__Audience
          valueFrom:
            configMapKeyRef:
              name: movie-microservices-config
              key: JWT_AUDIENCE
        - name: Jwt__ExpirationMinutes
          valueFrom:
            configMapKeyRef:
              name: movie-microservices-config
              key: JWT_EXPIRATION_MINUTES
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: movie-microservices
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: user-service-hpa
  namespace: movie-microservices
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user-service-deployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
