apiVersion: apps/v1
kind: Deployment
metadata:
  name: watchlist-service-deployment
  namespace: movie-microservices
spec:
  replicas: 2
  selector:
    matchLabels:
      app: watchlist-service
  template:
    metadata:
      labels:
        app: watchlist-service
    spec:
      containers:
      - name: watchlist-service
        image: REPLACE_WITH_YOUR_REGISTRY/movie-microservices/watchlist-service:latest
        ports:
        - containerPort: 3003
        env:
        - name: PORT
          value: "3003"
        - name: ENVIRONMENT
          value: "production"
        - name: DATABASE_HOST
          value: "watchlist-db-service"
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: watchlist-db-secret
              key: username
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: watchlist-db-secret
              key: password
        - name: DATABASE_DBNAME
          valueFrom:
            secretKeyRef:
              name: watchlist-db-secret
              key: database
        - name: DATABASE_SSLMODE
          value: "disable"
        - name: REDIS_HOST
          value: "redis-service"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
          value: ""
        - name: REDIS_DB
          value: "0"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: key
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3003
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 3003
          initialDelaySeconds: 5
          periodSeconds: 5
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: watchlist-service
  namespace: movie-microservices
spec:
  selector:
    app: watchlist-service
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: watchlist-service-hpa
  namespace: movie-microservices
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: watchlist-service-deployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
